services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    image: wittysmirk/gymjournal-app:v1 
    ports:
      - 8080:8080
    env_file:
      - .env
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    restart: unless-stopped
    image: wittysmirk/gymjournal-frontend:v1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
